/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppLocationsIndexRouteImport } from './pages/_app/locations/index'
import { Route as AppEpisodesIndexRouteImport } from './pages/_app/episodes/index'
import { Route as AppIndexIndexRouteImport } from './pages/_app/_index/index'
import { Route as AppIndexCharacterCharacterIdIndexRouteImport } from './pages/_app/_index/character/$characterId/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEpisodesIndexRoute = AppEpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppIndexIndexRoute = AppIndexIndexRouteImport.update({
  id: '/_index/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppIndexCharacterCharacterIdIndexRoute =
  AppIndexCharacterCharacterIdIndexRouteImport.update({
    id: '/_index/character/$characterId/',
    path: '/character/$characterId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexIndexRoute
  '/episodes': typeof AppEpisodesIndexRoute
  '/locations': typeof AppLocationsIndexRoute
  '/character/$characterId': typeof AppIndexCharacterCharacterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexIndexRoute
  '/episodes': typeof AppEpisodesIndexRoute
  '/locations': typeof AppLocationsIndexRoute
  '/character/$characterId': typeof AppIndexCharacterCharacterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/_index/': typeof AppIndexIndexRoute
  '/_app/episodes/': typeof AppEpisodesIndexRoute
  '/_app/locations/': typeof AppLocationsIndexRoute
  '/_app/_index/character/$characterId/': typeof AppIndexCharacterCharacterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/episodes' | '/locations' | '/character/$characterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/episodes' | '/locations' | '/character/$characterId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_index/'
    | '/_app/episodes/'
    | '/_app/locations/'
    | '/_app/_index/character/$characterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/locations/': {
      id: '/_app/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/episodes/': {
      id: '/_app/episodes/'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof AppEpisodesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_index/': {
      id: '/_app/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_index/character/$characterId/': {
      id: '/_app/_index/character/$characterId/'
      path: '/character/$characterId'
      fullPath: '/character/$characterId'
      preLoaderRoute: typeof AppIndexCharacterCharacterIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexIndexRoute: typeof AppIndexIndexRoute
  AppEpisodesIndexRoute: typeof AppEpisodesIndexRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
  AppIndexCharacterCharacterIdIndexRoute: typeof AppIndexCharacterCharacterIdIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexIndexRoute: AppIndexIndexRoute,
  AppEpisodesIndexRoute: AppEpisodesIndexRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
  AppIndexCharacterCharacterIdIndexRoute:
    AppIndexCharacterCharacterIdIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
