/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppLocationsIndexRouteImport } from './pages/_app/locations/index'
import { Route as AppEpisodesIndexRouteImport } from './pages/_app/episodes/index'
import { Route as AppCharactersIndexRouteImport } from './pages/_app/characters/index'
import { Route as AppLocationsLocationIdIndexRouteImport } from './pages/_app/locations/$locationId/index'
import { Route as AppEpisodesEpisodeIdIndexRouteImport } from './pages/_app/episodes/$episodeId/index'
import { Route as AppCharactersCharacterIdIndexRouteImport } from './pages/_app/characters/$characterId/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEpisodesIndexRoute = AppEpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLocationsLocationIdIndexRoute =
  AppLocationsLocationIdIndexRouteImport.update({
    id: '/locations/$locationId/',
    path: '/locations/$locationId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppEpisodesEpisodeIdIndexRoute =
  AppEpisodesEpisodeIdIndexRouteImport.update({
    id: '/episodes/$episodeId/',
    path: '/episodes/$episodeId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppCharactersCharacterIdIndexRoute =
  AppCharactersCharacterIdIndexRouteImport.update({
    id: '/characters/$characterId/',
    path: '/characters/$characterId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/characters': typeof AppCharactersIndexRoute
  '/episodes': typeof AppEpisodesIndexRoute
  '/locations': typeof AppLocationsIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdIndexRoute
  '/episodes/$episodeId': typeof AppEpisodesEpisodeIdIndexRoute
  '/locations/$locationId': typeof AppLocationsLocationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/characters': typeof AppCharactersIndexRoute
  '/episodes': typeof AppEpisodesIndexRoute
  '/locations': typeof AppLocationsIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdIndexRoute
  '/episodes/$episodeId': typeof AppEpisodesEpisodeIdIndexRoute
  '/locations/$locationId': typeof AppLocationsLocationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/characters/': typeof AppCharactersIndexRoute
  '/_app/episodes/': typeof AppEpisodesIndexRoute
  '/_app/locations/': typeof AppLocationsIndexRoute
  '/_app/characters/$characterId/': typeof AppCharactersCharacterIdIndexRoute
  '/_app/episodes/$episodeId/': typeof AppEpisodesEpisodeIdIndexRoute
  '/_app/locations/$locationId/': typeof AppLocationsLocationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/episodes'
    | '/locations'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/locations/$locationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/episodes'
    | '/locations'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/locations/$locationId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/characters/'
    | '/_app/episodes/'
    | '/_app/locations/'
    | '/_app/characters/$characterId/'
    | '/_app/episodes/$episodeId/'
    | '/_app/locations/$locationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/locations/': {
      id: '/_app/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/episodes/': {
      id: '/_app/episodes/'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof AppEpisodesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/characters/': {
      id: '/_app/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/locations/$locationId/': {
      id: '/_app/locations/$locationId/'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof AppLocationsLocationIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/episodes/$episodeId/': {
      id: '/_app/episodes/$episodeId/'
      path: '/episodes/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof AppEpisodesEpisodeIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/characters/$characterId/': {
      id: '/_app/characters/$characterId/'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof AppCharactersCharacterIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
  AppEpisodesIndexRoute: typeof AppEpisodesIndexRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
  AppCharactersCharacterIdIndexRoute: typeof AppCharactersCharacterIdIndexRoute
  AppEpisodesEpisodeIdIndexRoute: typeof AppEpisodesEpisodeIdIndexRoute
  AppLocationsLocationIdIndexRoute: typeof AppLocationsLocationIdIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
  AppEpisodesIndexRoute: AppEpisodesIndexRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
  AppCharactersCharacterIdIndexRoute: AppCharactersCharacterIdIndexRoute,
  AppEpisodesEpisodeIdIndexRoute: AppEpisodesEpisodeIdIndexRoute,
  AppLocationsLocationIdIndexRoute: AppLocationsLocationIdIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
